version: "3.9"

# ================================ #
# VOLUMES
# ================================ #
volumes:
  kong_prefix_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kong_tmp_vol:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mongo_data: {}
  redis_data: {}
  insight_data: {}
  grafana-storage: {}

# ================================ #
# NETWORKS
# ================================ #
networks:
  kong-net:  
    driver: bridge
  redis-net: 
    driver: bridge

services:
  # ================================ #
  # INFRASTRUCTURE (Zookeeper, Kafka)
  # ================================ #
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kong-net
 
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9094:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - kong-net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    restart: on-failure
  # ================================ #
  # KONG GATEWAY (DB-less mode)
  # ================================ #
  kong:
    container_name: kong
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-root}" 
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yaml
      
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
    ports:
      - "8000:8000"
      - "8443:8443"
      - "127.0.0.1:8001:8001"
      - "127.0.0.1:8444:8444"
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure

  # ================================ #
  # DATABASES (Mongo, Redis)
  # ================================ #
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - kong-net
      - redis-net
 
  redis-server:
    image: redis:latest
    container_name: my-redis
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    networks:
      - redis-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: on-failure
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # ================================ #
  # MICROSERVICES
  # ================================ #
  auth-service:
    build: ./backend/auth-service
    container_name: auth-service
    env_file:
      - ./backend/auth-service/.env
    ports:
      - 8081:8081
    depends_on:
      - kafka
      - mongodb
      - redis-server 
 
    networks:
      - redis-net
      - kong-net
 
  upload-service:
    build: ./backend/upload-service
    container_name: upload-service
    env_file:
      - ./backend/upload-service/.env
    ports:
      - 8089:8089
    depends_on:
      - kafka
      - mongodb
      - redis-server 
 
    networks:
      - redis-net  
      - kong-net
 
  notification-service:
    build: ./backend/notification-service
    container_name: notification-service
    env_file:
      - ./backend/notification-service/.env
    ports:
      - 8084:8084
    depends_on:
      - kafka
      - mongodb
      - redis-server 
 
    networks:
      - redis-net  
      - kong-net
 
  post-service:
    build: ./backend/post-service
    container_name: post-service
    env_file:
      - ./backend/post-service/.env
    ports:
      - 8087:8087
    depends_on:
      - kafka
      - mongodb
      - redis-server 
 
    networks:
      - redis-net  
      - kong-net
 
  message-service:
    build: ./backend/message-service
    container_name: message-service
    env_file:
      - ./backend/message-service/.env
    ports:
      - 8093:8093
    depends_on:
      - kafka
      - mongodb
      - redis-server 
 
    networks:
      - redis-net  
      - kong-net
 
  recomment-service:
    build: ./backend/recomment-service
    container_name: recomment-service
    env_file:
      - ./backend/recomment-service/.env
    ports:
      - "8086:8086"
    depends_on:
      - kafka
      - mongodb
      - redis-server 
    networks:
      - redis-net  
      - kong-net
    restart: on-failure